
export const stickers = [
    { name: 'Crying', file: '3bcjcg.gif' },
    { name: 'Curious Cat', file: 'xky7kj.gif' },
    { name: 'Sleeping', file: '65y8p2.gif' },
    { name: 'Heartbroken Cry', file: 'unuqao.gif' },
    { name: 'Dazed Dog', file: 'qmx674.gif' },
    { name: 'Dog with Leash', file: 'qa67b.gif' },
    { name: 'I will always be in the rain', file: 'fpcw82.gif' },
    { name: 'Cat Wink', file: 'mwbohq.gif' },
    { name: 'It\'s me at the door', file: 'n8b45y.gif' },
    { name: 'Lick you', file: 'k3rvzp.gif' },
    { name: 'Sad but not saying', file: 'j6xhgd.gif' },
    { name: 'Fell down', file: 'ojbum6.gif' },
    { name: 'Shocked', file: 'i6tnyl.gif' },
    { name: 'Cheering', file: 'js4kpb.jpeg' },
    { name: 'Dog wiping tears', file: 'jm7csh.jpeg' },
    { name: 'Marry me', file: 'ukfh8f.jpeg' },
    { name: 'Delicious', file: 'vutu7h.jpeg' },
    { name: 'Walking away flatly', file: '8xxu5t.jpeg' },
    { name: 'Sleeping alone', file: 'kli03s.jpeg' },
    { name: 'Swinging Cat', file: '6ltvz4.gif' },
    { name: 'Answer the phone', file: 'i2wm9r.jpeg' },
    { name: 'Spinning', file: 'tp2tjz.gif' },
    { name: 'What are you doing', file: 'xs3k95.gif' },
    { name: 'Pouting', file: 'jv5z2n.gif' },
    { name: 'Cat Screaming', file: 'e7l8v5.jpeg' },
    { name: 'Tearing heart apart', file: 'hqiyoi.gif' },
    { name: 'Alert', file: 'klo9ow.gif' },
    { name: 'Giving roses', file: 'aq9h0i.jpeg' },
    { name: 'Dog tilting head', file: 'eeuy10.gif' },
    { name: 'Guilty', file: 'emg4sq.gif' },
    { name: 'Everyone dies', file: '9z1p3d.jpeg' },
    { name: 'Taking notes', file: 'h3n0pn.jpeg' },
    { name: 'Winking at you', file: 'w0mg2l.jpeg' },
    { name: 'Suddenly nervous', file: 'n8r34l.jpeg' },
    { name: 'Angry', file: 'yb8av3.jpeg' },
    { name: 'Crying a river', file: 'jlwt6c.gif' },
    { name: 'Honest', file: 'bnaqpa.jpeg' },
    { name: 'Tactical daze', file: 'zbmdsp.jpeg' },
    { name: 'Dog playing with water', file: 'i3g5jx.gif' },
    { name: 'Jaw drop', file: 'sxkriu.gif' },
    { name: 'Patrolling', file: 'gwmadt.jpeg' },
    { name: 'Want', file: 'lzmdlb.jpeg' },
    { name: 'Puffy cheeks', file: '2ls2jr.jpeg' },
    { name: 'Being honest', file: 'ip8ujc.jpeg' },
    { name: 'Angry dog', file: 'cwsjuf.jpeg' },
    { name: 'Do you miss me', file: 'ar6yje.jpeg' },
    { name: 'Breaking down', file: 'l40mxw.jpeg' },
    { name: 'Stunned', file: 'kz8cz3.jpeg' },
    { name: 'Brain freeze', file: '4ok6uo.jpeg' },
    { name: 'Surprised', file: 'kfhbud.jpeg' },
    { name: 'Screaming', file: '2371d7.jpeg' },
    { name: 'Can\'t think', file: 'wqqdzk.jpeg' },
    { name: 'Pinching cheeks', file: 'nirppb.jpeg' },
    { name: 'Heart fluttering', file: 'q44ax3.jpeg' },
    { name: 'Knife', file: 'ttavfy.jpeg' },
    { name: 'I\'m here', file: '80mb6e.jpeg' },
    { name: 'Descending', file: '5s1ks0.jpeg' },
    { name: 'Playing on phone', file: 'si3ckt.jpeg' },
    { name: 'Question mark', file: 'isxybw.jpeg' },
    { name: 'Stare', file: 'wgc385.jpeg' },
    { name: 'Cold sweat', file: '3p3k7o.jpeg' },
    { name: 'Cute', file: 'z8afo0.jpeg' },
    { name: 'Cheering on', file: 'ga9vvk.jpeg' },
    { name: 'What', file: 'irxbvu.jpeg' },
    { name: 'Hanging', file: 'mocrwm.jpeg' },
    { name: 'Ascending', file: '1tbx46.jpeg' },
    { name: 'Stop thinking', file: 'x0hmpb.jpeg' },
    { name: 'Want a hug', file: 'ptf315.jpeg' },
    { name: 'I\'m fine', file: '7wpx0j.jpeg' },
    { name: 'Gloomy', file: 'wfsfqa.jpeg' },
    { name: 'Patching up', file: 'as9prr.jpeg' },
    { name: 'Confused', file: 'aj1vkl.jpeg' },
    { name: 'Cuddling', file: 'trgowd.jpeg' },
    { name: 'Police', file: '3afxl7.jpeg' },
    { name: 'Giving flowers', file: 'wfytdh.jpeg' },
    { name: 'Death penalty', file: 'gh304s.jpeg' },
    { name: 'Blushing', file: '5su7ib.gif' },
    { name: 'Shy', file: 'p49e82.gif' },
    { name: 'Excited roar', file: 'yr27px.gif' },
    { name: 'Swinging side to side', file: '50595y.gif' },
    { name: 'Energetic', file: 'yyn4ei.jpg' },
    { name: 'Protect', file: 'lulrbg.gif' },
    { name: 'Awkwardly sticking tongue out', file: 'lulrbg.gif' },
    { name: 'Packing and leaving', file: 'lli1cv.gif' },
    { name: 'Madly in love', file: 'kp46ma.gif' },
    { name: 'Spinning with joy', file: '9gck9y.gif' },
    { name: 'Is there someone else', file: 'v0ivql.gif' },
    { name: 'Crying and shaking', file: '149w27.gif' },
    { name: 'Running to baby', file: '4xftts.jpeg' },
    { name: 'Let\'s break up', file: '9m8r9n.jpeg' },
    { name: 'Baby doesn\'t miss me', file: 'czxnj0.jpeg' },
    { name: 'Hugging and rubbing', file: 'u0mnv0.gif' },
    { name: 'Making a face', file: 'a05ch7.gif' },
    { name: 'Swaying to the music', file: 't6v7wy.gif' },
    { name: 'Completely heartbroken', file: 'vryih1.gif' },
    { name: 'Confused', file: 'e9ad7m.gif' },
    { name: 'If you don\'t miss me, I\'ll write it down', file: 'lfiofg.jpeg' },
    { name: 'Devastated', file: 'uywru4.gif' },
    { name: 'I love my baby so much', file: 'zqwmxf.jpeg' },
    { name: 'So angry', file: 'hsc3rv.gif' },
    { name: 'Crying alone', file: '60m9mz.gif' },
    { name: 'Sticking together', file: 'di0wiz.gif' },
    { name: 'I\'m fine', file: 'e29g2s.jpeg' },
    { name: 'No longer depressed', file: 'ei0y9c.jpeg' },
    { name: 'Can\'t sleep', file: 'q8gjo1.gif' },
    { name: 'Running away quickly', file: 'rsxpq9.gif' },
    { name: 'Getting carried away', file: 'kv2ubl.gif' },
    { name: 'Pathetic', file: 'fyrnta.gif' },
    { name: 'Hitting you', file: 'rf7g7e.gif' },
    { name: 'Arrogant', file: 'hmdqt7.jpeg' },
    { name: 'Blushing furiously', file: 'uc3bpf.gif' },
    { name: 'Crying into hands', file: 'l2821c.gif' },
    { name: 'Go away', file: 'hnl3yj.gif' },
    { name: 'Fuming', file: '0kayvn.jpeg' },
    { name: 'Drooling', file: '2e85p2.gif' },
    { name: 'Ignoring each other', file: 'dxfgse.gif' },
    { name: 'Shaking head vigorously', file: 'ir62vg.gif' },
    { name: 'So delicious', file: 'p10mmg.gif' },
    { name: 'Dozing off', file: 'x6jetu.gif' },
    { name: 'All my money for you', file: '3mwh7f.gif' },
    { name: 'Clown juggling', file: 'g20uxy.gif' },
    { name: 'Giggling foolishly', file: '0dbp6y.jpeg' },
    { name: 'You\'re so weird', file: 'e4hvp3.gif' },
    { name: 'Thinking', file: 't9mwfh.jpeg' },
    { name: 'Dog tilting head', file: 'pp0whr.gif' },
    { name: 'Waiting obediently', file: 'nfp49y.gif' },
    { name: 'Angry and silent', file: '3ckb8d.jpeg' },
    { name: 'So angry', file: 'ct45xc.gif' },
    { name: 'Crushing', file: 'bsgwmk.gif' },
    { name: 'Comfort me', file: 'atuwe8.jpeg' },
    { name: 'Comfort me now', file: 'fxg0gz.gif' },
    { name: 'You made me angry', file: 'tw7lzl.jpeg' },
    { name: 'Furious', file: 'bafz6c.gif' },
    { name: 'Flipping table', file: 'ipmucn.gif' },
    { name: 'Dragon\'s wrath', file: '5ojelf.jpeg' },
    { name: 'Losing temper', file: '5kuo0o.gif' },
    { name: 'Don\'t underestimate me', file: 'k90z1n.jpeg' },
    { name: 'Something is wrong with this world', file: 'wdv1p9.jpeg' },
    { name: 'I hate you', file: '943acw.jpeg' },
    { name: 'Rubbing vigorously', file: '2x3d8w.gif' },
    { name: 'Cold sweat', file: 'zurf8e.jpeg' },
    { name: 'I won\'t cry', file: '5ron91.jpeg' },
    { name: 'Looking around', file: '9bx4tx.jpeg' },
    { name: 'What are you doing', file: 'y5pmur.jpeg' },
    { name: 'Kiss', file: 'm2qwf0.jpeg' },
    { name: 'I\'m pretending', file: 'jtuxg5.jpeg' },
    { name: 'Angry', file: 'sq58nx.jpeg' },
    { name: 'Hmph!', file: 'snbuvc.jpeg' },
    { name: 'Oh?', file: 'orw8xz.jpeg' },
    { name: 'It\'s okay', file: 'espgmb.jpeg' },
    { name: 'Furious', file: 'kw1pu1.jpeg' },
    { name: 'Flowers for you', file: 'm5wiys.jpeg' },
    { name: 'What are you doing', file: '1hngar.jpeg' },
    { name: 'Crying', file: 'ws1m8r.jpeg' },
    { name: 'Need to poop', file: 'jlvon3.jpeg' },
    { name: 'Baby is angry', file: 'rvwu19.jpeg' },
    { name: 'Baby, it\'s me at the door', file: 'rkbu7k.jpeg' },
    { name: 'Get lost', file: 'hcilav.jpeg' },
    { name: 'Angry', file: 'rabox8.jpeg' },
    { name: 'Studying', file: '3q002r.jpeg' },
    { name: 'What\'s going on', file: 'iypdat.jpeg' },
    { name: 'I miss you so much', file: '2np5s0.jpeg' },
    { name: 'Waiting for a reply', file: 'z8215g.jpeg' },
    { name: 'Heart fluttering message', file: 'ukoode.jpeg' },
    { name: 'Rubbing face', file: '3ieo1z.jpeg' },
    { name: 'I miss you so much', file: 'sbowkb.jpeg' },
    { name: 'Thinking of you secretly', file: 'zrzqaz.jpeg' },
    { name: 'Leave the house to me', file: 'obndh9.jpeg' },
    { name: 'Sipping', file: 'xtl8ji.jpeg' },
    { name: 'Rubbing belly', file: '8kuxyq.jpeg' },
    { name: 'Patting head', file: '2ay3nv.jpeg' },
    { name: 'Proud', file: '2kcrby.jpeg' },
    { name: 'I\'m going to throw a tantrum', file: '8vo7w6.jpeg' },
    { name: 'Coming right away', file: 'z1kh7c.jpeg' },
    { name: 'Shocked and confused', file: '023udf.jpeg' },
    { name: 'Dazed', file: 'jz3yjx.jpeg' },
    { name: 'Speechless', file: 'osy8cj.jpeg' },
    { name: 'Sleepy', file: 'mslwpn.jpeg' },
    { name: 'Scared', file: 'vq6rfl.jpeg' },
    { name: 'Confused', file: '4vu47v.jpeg' },
    { name: 'So happy', file: '5ekfqq.jpeg' },
    { name: 'Don\'t look at me', file: 'o85ihe.jpeg' },
    { name: 'Okay', file: 'z5uk1x.jpeg' },
    { name: 'Good', file: 'xvvbzu.jpeg' },
    { name: 'Dark face', file: 's9nj7c.jpeg' },
    { name: 'Seducing', file: 'g6n1ih.jpeg' },
    { name: 'Greeting', file: 'klju8f.jpeg' },
    { name: 'Hehe', file: 'tlr86z.jpeg' },
    { name: 'Sentenced to death', file: 'kmngu2.jpeg' },
    { name: 'Cuddling with you', file: 'hgqp7m.jpeg' },
    { name: 'Bringing flowers to see baby', file: 'vttaf9.jpeg' },
    { name: 'Missing you to tears', file: 'jz9sw3.jpeg' },
    { name: 'Wary', file: '7ufxvj.jpeg' },
    { name: 'Not talking to you anymore', file: 'm9uye6.jpeg' },
    { name: 'Quite speechless', file: '6b8fsu.jpeg' },
    { name: 'Painfully giving up', file: 'tx58j7.gif' },
    { name: 'Peacefully closing eyes', file: 'qkm36q.jpeg' },
    { name: 'Nodding', file: 'd5g7o9.gif' },
    { name: 'Cute head tilt', file: 'ro3rbc.gif' },
    { name: 'Disappointed', file: 'tgjxjw.gif' },
    { name: 'Don\'t know', file: '4uc50x.gif' },
    { name: 'Waiting for a reply', file: 'q63nfd.gif' },
    { name: 'Love you forever', file: '51jw25.jpeg' },
    { name: 'Looking closely', file: 'ig3hoz.gif' },
    { name: 'Innocent cat face', file: 'wgead8.gif' },
    { name: 'Offering flowers', file: 'd9v19v.jpeg' },
    { name: 'I will always be watching you', file: 'ldqj4q.png' },
    { name: 'Catch', file: 'd23lh8.gif' },
    { name: 'Staring intently', file: 'ihqa29.png' },
    { name: 'Crying puppy', file: 'trbenv.gif' },
    { name: 'Big sip', file: 'b94amf.gif' },
    { name: 'Obedient cat', file: 'd1g8hn.gif' },
    { name: 'Rubbing', file: 'qz8230.gif' },
    { name: 'Kissing', file: 'l7cpd2.jpeg' },
    { name: 'On the verge of tears', file: 'q46fv4.jpeg' },
    { name: 'Excitedly holding phone', file: '3kevx3.jpeg' },
    { name: 'Giving you flowers', file: '38zxz6.jpeg' },
    { name: 'Eyes sparkling with love', file: 'rxe26m.jpeg' },
    { name: 'Caught it', file: 'gsn3vp.jpeg' },
    { name: 'Shy and flustered', file: 'b6o0z0.jpeg' },
    { name: 'Heart fluttering like crazy', file: 'texmzf.jpeg' },
    { name: 'I\'m dead', file: 'x8syam.jpeg' },
    { name: 'Quite speechless', file: '1vyeto.jpeg' },
    { name: 'Disgusted face', file: 'u0fklh.jpeg' },
    { name: 'Rubbing vigorously in arms', file: 'a9eflk.jpeg' },
    { name: 'Wink', file: '05vzg1.jpeg' },
    { name: 'Hug', file: 'o6bg6b.jpeg' },
    { name: 'Baby I\'m here', file: 'zhvszp.jpeg' },
    { name: 'Love signal', file: '19k3to.jpeg' },
    { name: 'Acting cute', file: 'pkdfjo.jpeg' },
    { name: 'Overwhelmed by cuteness', file: 'w7truh.jpeg' },
    { name: 'You\'re so cute', file: '9lfjlu.jpeg' },
    { name: 'Checking up on you', file: 'r26s3i.jpeg' },
    { name: 'You\'re a bad person', file: '7twkez.jpeg' },
    { name: 'Being petted', file: 'hxj63t.jpeg' },
    { name: 'Licking', file: 'sm6ja2.jpeg' },
    { name: 'Acting cute and spoiled', file: 'o5re2t.jpeg' },
    { name: 'Crying in a ball', file: 'go345o.jpeg' },
    { name: 'Are you okay', file: 'm5jt11.jpeg' },
    { name: 'Stay with me', file: 'i91ww7.jpeg' },
    { name: 'Crying while waiting for a message', file: '0a64r3.jpeg' },
    { name: 'Jealous', file: 'ajl3yd.jpeg' },
    { name: 'No one loves me', file: 'jdhb1n.jpeg' },
    { name: 'Just keep ignoring me', file: 'r57sc0.jpeg' },
    { name: 'What are you doing', file: 'z1hvcd.gif' },
    { name: 'No horny', file: 'fy4fn2.jpeg' },
    { name: 'Stalking', file: 'shjjc5.jpeg' },
    { name: 'Pouting', file: 'ypkaog.gif' },
    { name: 'Love you', file: 'h5o1k5.jpeg' },
    { name: 'Heartbroken', file: 'idfqtx.jpeg' },
    { name: 'Holding a grudge', file: 'co9rcr.gif' },
    { name: 'Nervous', file: 'tzfysx.gif' },
    { name: 'Begging for mercy', file: 'c9w1e5.gif' },
    { name: 'Thinking', file: 'o2bubj.gif' },
    { name: 'Good night', file: 'o0ftqk.gif' },
    { name: 'Hungry', file: 'tcxvef.gif' },
    { name: 'Sigh', file: 'a8gvwh.gif' },
    { name: 'Cuddling', file: 'hv5qhc.gif' },
    { name: 'Out of the loop', file: '3zyvhr.jpeg' },
    { name: 'Blushing', file: '9fwivr.gif' },
    { name: 'In love', file: 'h7q2nx.gif' },
    { name: 'What are you doing', file: '6rh59t.jpeg' },
    { name: 'I\'m here', file: 'k5h60v.jpeg' },
    { name: 'Questioning oh', file: '6r5drj.gif' },
    { name: 'Do you miss me', file: 'mch0ue.jpeg' },
    { name: 'Looking around', file: '8if2pl.gif' },
    { name: 'Licking', file: '9m45uq.gif' },
    { name: 'Unsure', file: 'ay8jc5.jpeg' },
    { name: 'Not convinced', file: 'o7pukp.gif' },
    { name: 'Trying not to laugh', file: 'awr3um.gif' },
    { name: 'Dissatisfied', file: 'vvyfk7.jpeg' },
    { name: 'Eating', file: 'zq5cbn.gif' },
    { name: 'Withdrawn', file: 'zk8az7.gif' },
    { name: 'Singing', file: 'ia89om.gif' },
    { name: 'Vomiting', file: 'rdtyuu.gif' },
    { name: 'Question mark', file: '33zta8.gif' },
    { name: 'Sleeping', file: 'x7wmhx.gif' },
    { name: 'Wiping tears', file: 'k98o1l.gif' },
    { name: 'Leaving', file: 'h1dbrk.gif' },
    { name: 'Bowing', file: 'r5ecnl.gif' },
    { name: 'Speechless', file: '12f83p.gif' },
    { name: 'Together forever', file: 'ue0212.gif' },
    { name: 'I\'m a joke', file: '84t5m1.gif' },
    { name: 'Go out with me', file: 'poxosw.gif' },
    { name: 'Eating', file: 'j1az40.gif' },
    { name: 'I\'m stupid', file: 'hwmzer.jpeg' },
    { name: 'Giving roses', file: '1uv9y2.jpeg' },
    { name: 'Annoyed', file: 'baw1ev.gif' },
    { name: 'Sitting up', file: 'r2xoge.jpeg' },
    { name: 'Being honest', file: '7i0klk.jpeg' },
    { name: 'Proud', file: 'ynpuu2.gif' },
    { name: 'Happy', file: 'slcf6y.gif' },
    { name: 'Wow', file: '7k826r.gif' },
    { name: 'Sleepy', file: 'pk9geg.gif' },
    { name: 'Waiting for message', file: 'uh30cd.gif' },
    { name: 'I\'m a puppy', file: 'o2j51i.gif' },
    { name: 'Here', file: 'k25jhb.gif' },
    { name: 'Craving', file: '04x57o.gif' },
    { name: 'Sad', file: 'damocy.gif' },
    { name: 'Sweating', file: 'rmejps.gif' },
    { name: 'Nodding', file: 'y7lpqn.gif' },
    { name: 'Admiring', file: 'icopa9.gif' },
    { name: 'Sulking', file: 'ataiez.gif' },
    { name: 'I\'m fine', file: '0q0gb4.gif' },
    { name: 'Surprise', file: '9rexzn.gif' },
    { name: 'Dejected', file: 'qcxnbl.gif' },
    { name: 'Hmph', file: 'zsg79l.gif' },
    { name: 'Yay', file: 'rneasm.gif' },
    { name: 'Seeking attention', file: 'kc8bgy.jpg' },
    { name: 'Apologizing', file: '3exsz6.jpg' },
    { name: 'Questioning', file: 'n3pdvn.jpg' },
    { name: 'Mischievous', file: 'v27ozl.jpg' },
    { name: 'Hoping', file: 'y5c5gi.jpg' },
    { name: 'Go for it', file: '08pu9k.jpg' },
    { name: 'Understood', file: 'wm5pcq.jpg' },
    { name: 'Wagging tail', file: 'nvv03u.gif' },
    { name: 'Rubbing', file: 'wnp9jl.gif' },
    { name: 'Peeking', file: 'wmjn8b.gif' },
    { name: 'Fainting', file: 'tzmus0.gif' },
    { name: 'Relaxed', file: 'wnp9jl.gif' },
    { name: 'Seducing', file: 'pdp3lv.jpg' },
    { name: 'Yay', file: 'h0jeiw.gif' },
    { name: 'Pathetic', file: '3nvu7b.gif' },
    { name: 'Can\'t explain', file: 't0ajhn.jpeg' },
    { name: 'Hearing forever', file: 'tpo0e2.jpeg' },
    { name: 'Interested', file: 'vkdlit.jpeg' },
    { name: 'Observing secretly', file: '67xkk5.jpeg' },
    { name: 'Taking notes', file: 'f24nqv.jpeg' },
    { name: 'Wiping tears', file: 'e8kugb.jpeg' },
    { name: 'Good', file: 'y4hee4.jpeg' },
    { name: 'Holding back tears', file: 'd5m1in.jpeg' },
    { name: 'Dependent', file: '7h1nbc.gif' },
    { name: 'Patting head', file: '7yovpn.gif' },
    { name: 'Tilting head', file: 'yj5xmj.gif' },
    { name: 'Waiting', file: 'hhmm9x.jpeg' },
    { name: 'Bored', file: 'ed3jqc.gif' },
    { name: 'Are you looking for me', file: 'p65ev3.jpeg' },
    { name: 'Mixed feelings', file: 'ryt49l.gif' },
    { name: 'Yawning', file: 'twadvx.gif' },
    { name: 'Raising hand', file: 'raw3ta.jpeg' },
    { name: 'Dazed and blushing', file: 'tx1kgp.jpeg' },
    { name: 'Being ignored', file: 'ibf98l.jpeg' },
    { name: 'Hate you', file: 'o3154o.jpeg' },
    { name: 'Complaining', file: 'mvfuos.jpeg' },
    { name: 'Sad but not saying', file: '37usdl.gif' },
    { name: 'It\'s me at the door', file: 'sb7zm5.gif' },
    { name: 'Confused', file: 'vu4mfg.gif' },
    { name: 'Inferior', file: 'cop2n5.gif' },
    { name: 'Looking forward to it', file: 'zc7nnz.gif' },
    { name: 'Sleepy', file: 'k6cb6j.gif' },
    { name: 'Angry', file: 'ceoy5y.gif' },
    { name: 'Cheers', file: '5j88sm.gif' },
    { name: 'Question mark', file: '9jpyl6.gif' },
    { name: 'Showing off', file: 'q8rl9n.gif' },
    { name: 'Running', file: 'awnb0x.gif' },
    { name: 'Working', file: 'djb49f.gif' },
    { name: 'Hmph, fine', file: 'tl96yv.jpeg' },
    { name: 'Going to hang myself', file: 'lvsh6w.jpeg' },
    { name: 'I\'m a joke', file: 'pmf4cp.gif' },
    { name: 'I\'m a little angry', file: 'ntjlcs.gif' },
    { name: 'Good night', file: 'vpsd3q.gif' },
    { name: 'Waiting', file: '6h5apb.gif' },
    { name: 'Like you', file: 'elhr14.gif' },
    { name: 'Dependent', file: 'r9fg6b.gif' },
    { name: 'Admiring', file: 'wjl5u1.gif' },
    { name: 'Crying loudly', file: 'sks590.gif' },
    { name: 'Tears', file: 'blnrmg.jpeg' },
    { name: 'Deceived', file: 'qakkk8.jpeg' },
    { name: 'Hmph', file: '1pwe2z.gif' },
    { name: 'Okay then', file: 'vpxfm3.jpeg' },
    { name: 'Sitting up', file: 'isb6xd.jpeg' },
    { name: 'Reflecting', file: '1ran24.jpg' },
    { name: 'Sister misses you', file: 'qfl5kq.jpg' },
    { name: 'Sister likes you', file: 'l0px5o.jpg' },
    { name: 'Sister, stop working', file: 'dptsec.jpg' },
    { name: 'Please, please', file: 'ia901u.jpg' },
    { name: 'I\'ll find a way to deal with you', file: 'z4zw1t.jpeg' },
    { name: 'Are you telling me what to do', file: 'v9ggjd.jpeg' },
    { name: 'Can you love me', file: '61mdxy.jpeg' },
    { name: 'Isn\'t it enough that I\'m wrong', file: 'e20jeu.jpeg' },
    { name: 'Don\'t be angry anymore', file: 'ktzqnv.jpeg' },
    { name: 'Hug', file: 'iwluvn.gif' },
    { name: 'Relaxed', file: 'l57ew2.gif' },
    { name: 'Guilty', file: 'bxohqt.gif' },
    { name: 'What can you do to me', file: 'tnry4b.jpeg' },
    { name: 'Say you love me', file: '0h55qr.jpeg' },
    { name: 'Seducing me again', file: 'ioug79.jpeg' },
    { name: 'My heart is dead', file: '4juksw.jpeg' },
    { name: 'Is the work done', file: '9s4jol.jpeg' },
    { name: 'Impressed you, huh', file: '7yez84.jpeg' },
    { name: 'Spitting as I pass by', file: 'qeosjj.jpeg' },
    { name: 'You hurt me', file: 'ykiprx.jpeg' },
    { name: 'You\'re so mean to me', file: 'edvguw.jpeg' },
    { name: 'You\'ve fallen for someone else, haven\'t you', file: 'aqqy4m.jpeg' },
    { name: 'What did I do wrong', file: 'bfukx4.jpeg' },
    { name: 'Don\'t ask where I am', file: 'bt1d0z.gif' },
    { name: 'I\'m so fragile', file: '218jjv.jpeg' },
    { name: 'Why aren\'t you replying', file: 'nif2nw.gif' },
    { name: 'Jealous', file: 'k11zz3.gif' },
    { name: 'You\'re good at this', file: 'rnt41h.gif' },
    { name: 'Makes me want to curse', file: '1ez1s5.gif' },
    { name: 'So what', file: 'qgzlgf.gif' },
    { name: 'You\'re so nice', file: 'navxhg.gif' },
    { name: 'So unlucky', file: 'xvi105.gif' },
    { name: 'I\'m so done', file: '2uz6xq.gif' },
    { name: 'Flirting', file: 'ibo6zd.gif' },
    { name: 'A complete mess', file: 'kifzut.jpeg' },
    { name: 'Don\'t tempt me', file: 'ihd1vw.gif' },
    { name: 'I don\'t understand', file: 'yu5a48.jpeg' },
    { name: 'Gotta go', file: 'slpnck.jpeg' },
    { name: 'Kiss me', file: 't0qgux.jpeg' },
    { name: 'Mixed feelings', file: 'h2wkfm.jpeg' },
    { name: 'Baby you?', file: 'i04dm0.jpeg' },
    { name: 'That\'s not what you said before', file: 'hzi7h6.jpeg' },
    { name: 'Crazier than me', file: '6u1xkh.jpeg' },
    { name: 'Empty', file: 'jnwccf.gif' },
    { name: 'Hanging', file: 'ddh045.gif' },
    { name: 'Running away', file: 'wo6e4i.gif' },
    { name: 'Being honest', file: '1cso2x.jpeg' },
    { name: 'Look, you\'re getting worked up again', file: 'tkgige.jpeg' },
    { name: 'Hurt', file: '29d7wj.jpeg' },
    { name: 'Thanks to me', file: 'dkbfx4.jpeg' },
    { name: 'Cursing me is like having a crush on me', file: 'd5cqkw.jpeg' },
    { name: 'Tapping your head', file: '0st2mm.jpeg' },
    { name: 'You won\'t be happy if I say it', file: 'kbtelx.jpeg' },
    { name: 'Perfunctory', file: 'v6eg3f.jpeg' },
    { name: 'I\'m a joke', file: 'r7n4jv.gif' },
    { name: 'Angry', file: '1rimc0.gif' },
    { name: 'Triggered', file: 'setyja.jpeg' },
    { name: 'Smug', file: 'acaulp.gif' },
    { name: 'Laughing out loud', file: '1fx82m.gif' },
    { name: 'Don\'t want to hear it', file: 'kizz8h.jpeg' },
    { name: 'Like you', file: 'exfc5h.gif' },
    { name: 'Pouting', file: 'pm2hnq.jpeg' },
    { name: 'Not a single thing I like to hear', file: 'o0q8gu.jpeg' },
    { name: 'I\'m a simp', file: '9sswjd.jpeg' },
    { name: 'Just bullying you', file: 'g835jn.gif' },
    { name: 'Playing dumb', file: 'z3qvwl.gif' },
    { name: 'None of your business', file: '1ow49t.jpeg' },
    { name: 'I\'ll shut up', file: '6bg6xh.jpeg' },
    { name: 'Master, your wish is my command', file: '6nrj2n.jpeg' },
    { name: 'Holding a grudge', file: 'jg1efv.jpeg' },
    { name: 'Guaranteed to mess up', file: 'h6mare.jpeg' },
    { name: 'Fine, I\'ll let you win', file: 'tnr7t2.jpeg' },
    { name: 'Okay', file: '3j0tpc.jpeg' },
    { name: 'That person is super in love with you', file: 'sab2u7.jpg' },
    { name: 'Still a big romantic', file: '694ww4.jpg' },
    { name: 'Next time for sure', file: 'txyeaw.jpg' },
    { name: 'Just curse me', file: 'ui2suf.jpg' },
    { name: 'You\'re amazing', file: '7gz7uo.jpg' },
    { name: 'Women have no reason', file: '8d1vd8.jpg' },
    { name: 'Behave online', file: 'an4s0g.jpg' },
    { name: 'Time to work', file: 'gc0v6d.jpg' },
    { name: 'Come to the company', file: 'qdqz4c.jpg' },
    { name: 'Keep seducing me', file: 'w45o52.jpg' },
    { name: 'Trying to make me angry on purpose?', file: '71vfsr.jpg' },
    { name: 'Can\'t do without me, right', file: 'gph0af.jpg' },
    { name: 'Okay, okay, okay', file: 'vdwqhi.jpg' },
    { name: 'Have you already fallen for me', file: '50o6hc.jpg' },
    { name: 'I should thank you then', file: 'rk6ym7.jpg' },
    { name: 'You shut up', file: '0vizzz.jpg' },
    { name: 'Lonely', file: 'tugb9c.jpg' },
    { name: 'Excited', file: 'z76d72.jpg' },
    { name: 'SM teasing', file: 'g34l5n.jpg' },
    { name: 'Go for it, you useless thing', file: 'oi47v8.jpg' },
    { name: 'Come to my bed', file: 'zg3o69.jpg' },
    { name: 'Let me see you shower', file: 'bhv2bf.jpg' },
    { name: 'I\'ll support you', file: '7owi7y.jpg' },
    { name: 'You made me laugh', file: 'fja2eh.jpg' },
    { name: 'Under your thumb', file: 'qzalbl.jpg' },
    { name: 'Fell in love with you', file: 'j1hcxf.jpg' },
    { name: 'I need to work hard', file: 'rp4dai.jpg' },
    { name: 'Can\'t understand', file: '19cyc5.jpg' },
    { name: 'Questioning', file: '2rs5u0.jpg' },
    { name: 'Weaklings, don\'t speak', file: '5ggaq2.jpg' },
    { name: 'Clingy', file: 'brones.jpg' },
    { name: 'Failure', file: 'oaul9e.jpg' },
    { name: 'Fighting', file: '1zdozf.jpg' },
    { name: 'What now', file: 'zn4fgs.jpeg' },
    { name: 'You are most precious', file: 'dm149i.jpg' },
    { name: 'You\'re so bad', file: 'cc9n4i.jpg' },
    { name: 'Don\'t mess with me', file: '8gfk07.jpg' },
];
